"""
Script para extrair cookies do YouTube do seu navegador.
Isso resolve o problema de "login required" do YouTube.

Execute este script uma vez antes de iniciar o bot:
    python extract_cookies.py

O script tentará extrair cookies do Chrome, Edge e Firefox automaticamente.
"""

import browser_cookie3
import json
from pathlib import Path

def extract_youtube_cookies():
    """Extrai cookies do YouTube de navegadores instalados"""
    
    cookies_file = Path(__file__).parent / "youtube_cookies.txt"
    
    print("🍪 Tentando extrair cookies do YouTube do seu navegador...\n")
    
    browsers = [
        ("Chrome", browser_cookie3.chrome),
        ("Edge", browser_cookie3.edge),
        ("Firefox", browser_cookie3.firefox),
        ("Opera", browser_cookie3.opera),
        ("Brave", browser_cookie3.brave),
    ]
    
    cookies_found = False
    
    for browser_name, browser_func in browsers:
        try:
            print(f"🔍 Tentando {browser_name}...")
            cookies = browser_func(domain_name='.youtube.com')
            
            # Converte para formato Netscape que o yt-dlp aceita
            with open(cookies_file, 'w', encoding='utf-8') as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file is generated by extract_cookies.py\n\n")
                
                cookie_count = 0
                for cookie in cookies:
                    if 'youtube.com' in cookie.domain:
                        # Formato: domain flag path secure expiration name value
                        f.write(f"{cookie.domain}\t")
                        f.write("TRUE\t" if cookie.domain.startswith('.') else "FALSE\t")
                        f.write(f"{cookie.path}\t")
                        f.write("TRUE\t" if cookie.secure else "FALSE\t")
                        f.write(f"{cookie.expires if cookie.expires else 0}\t")
                        f.write(f"{cookie.name}\t")
                        f.write(f"{cookie.value}\n")
                        cookie_count += 1
                
                if cookie_count > 0:
                    print(f"✅ {browser_name}: {cookie_count} cookies extraídos!")
                    cookies_found = True
                    break
                else:
                    print(f"⚠️  {browser_name}: Nenhum cookie do YouTube encontrado")
                    
        except Exception as e:
            print(f"❌ {browser_name}: {str(e)}")
            continue
    
    if cookies_found:
        print(f"\n✅ Cookies salvos em: {cookies_file}")
        print("✅ O bot agora pode usar o YouTube sem problemas de login!")
        print("\n⚠️  IMPORTANTE: Execute este script novamente se os cookies expirarem (geralmente após alguns meses)")
        return True
    else:
        print("\n❌ Não consegui extrair cookies de nenhum navegador.")
        print("\n📝 SOLUÇÃO ALTERNATIVA:")
        print("1. Instale a extensão 'Get cookies.txt LOCALLY' no seu navegador")
        print("2. Acesse youtube.com e faça login")
        print("3. Clique na extensão e baixe o arquivo cookies.txt")
        print("4. Renomeie para 'youtube_cookies.txt' e coloque na pasta do bot")
        return False

if __name__ == "__main__":
    print("=" * 60)
    print("   EXTRATOR DE COOKIES DO YOUTUBE PARA O BOT")
    print("=" * 60)
    print()
    
    try:
        success = extract_youtube_cookies()
        
        if success:
            print("\n" + "=" * 60)
            print("   AGORA PODE INICIAR O BOT!")
            print("=" * 60)
        else:
            print("\n" + "=" * 60)
            print("   USE A SOLUÇÃO ALTERNATIVA ACIMA")
            print("=" * 60)
            
    except Exception as e:
        print(f"\n❌ Erro inesperado: {e}")
        print("\nTente usar a solução alternativa mencionada acima.")
    
    input("\nPressione ENTER para fechar...")
